name: PR Quality Check - Maven Build and SonarQube Scan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonar-pr-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn install -f MyWebApp/pom.xml

    - name: SonarQube Scan (Pull Request)
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=my-Java-web-app
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      continue-on-error: true

    - name: Handle Quality Gate Result
      run: |
        if [ "${{ steps.sonarqube-quality-gate-check.outcome }}" == "failure" ]; then
          echo "⚠️ Warning: SonarQube Quality Gate FAILED, but PR check continues."
        else
          echo "✅ SonarQube Quality Gate PASSED for PR."
        fi
